name: Build

on:
    push:
        branches: [main]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      name: win
                      backend: WebView2
                      cpack_generator: WIX;ZIP
                    # - os: ubuntu-latest
                    #   name: linux
                    #   container: archlinux:base-devel
                    #   backend: WebKitGtk
                    #   cpack_generator: TGZ

        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup build dependencies (Arch)
              if: matrix.container == 'archlinux:base-devel'
              run: |
                  pacman --noconfirm -Syu cmake gcc git xorg-server-xvfb xorg-xwd openssh tmate dbus python gtk4 libadwaita webkitgtk-6.0 nodejs npm

            - name: Setup build dependencies (Windows)
              if: matrix.os == 'windows-latest'
              run: |
                  choco upgrade cmake --install-arguments='"ADD_CMAKE_TO_PATH=System"' -y
                  choco install wixtoolset -y
                  choco install nodejs-lts -y
                  refreshenv
              shell: powershell

            - name: Verify WiX installation(Windows)
              if: matrix.os == 'windows-latest'
              run: |
                  $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
                  Write-Host "WiX candle.exe location:"
                  Get-Command candle.exe -ErrorAction SilentlyContinue
                  Write-Host "WiX light.exe location:"
                  Get-Command light.exe -ErrorAction SilentlyContinue
              shell: powershell

            - name: Build(frontend)
              run: |
                  npm install -g pnpm
                  pnpm install
                  pnpm run build

            - name: Configure (CMake)
              run: cmake -B build -DCMAKE_BUILD_TYPE=Release -Dsaucer_backend=${{ matrix.backend }}

            - name: Build(CMake)
              run: cmake --build build --config Release --parallel

            - name: Package with CPack
              id: cpack
              run: |
                  cd build
                  cpack -G "${{ matrix.cpack_generator }}"
              continue-on-error: true

            - name: Display WiX logs (if failed)
              if: failure() && matrix.os == 'windows-latest' && steps.cpack.outcome == 'failure'
              run: |
                  echo "=== WiX Output Log ==="
                  if (Test-Path "build/_CPack_Packages/win64/WIX") {
                      Get-ChildItem -Recurse "build/_CPack_Packages/win64/WIX" -Filter "*.log" | ForEach-Object {
                          Write-Host "=== $($_.Name) ==="
                          Get-Content $_.FullName
                      }
                  } else {
                      echo "WIX directory not found"
                  }
                  echo ""
                  echo "=== All CPack files ==="
                  if (Test-Path "build/_CPack_Packages") {
                      Get-ChildItem -Recurse "build/_CPack_Packages"
                  }
              shell: powershell

            - name: Exit if cpack failed
              if: steps.cpack.outcome == 'failure'
              run: exit 1

            - name: Print build artifacts
              run: ls -la build/

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: TheHQProject-${{ matrix.name }}
                  path: |
                      build/TheHQProject-*.msi
                      build/TheHQProject-*.zip
                      build/TheHQProject-*.tar.gz
                  if-no-files-found: error
                  retention-days: 90
